### ISSUE TITLE
org.mule.common.security.oauth.OAuthState cannot be cast to org.mule.modules.salesforce.oauth.SalesforceOAuthConnectorOAuthState

### ISSUE THREAD

**Issue by ericparshall** [mulesoft/salesforce-connector#83]
I use a custom object store to manage my OAuth states.  While upgrading my Mule project to version 3.5 I had to modify my object store to work with OAuthState objects rather than SalesforceOAuthConnectorOAuthState.  The authorization process works and stores the oauth state that comes from the Salesforce connector.  However, when I try to do a Describe action or an Upsert action I get this error:

```
Root Exception stack trace:
java.lang.ClassCastException: org.mule.common.security.oauth.OAuthState cannot be cast to org.mule.modules.salesforce.oauth.SalesforceOAuthConnectorOAuthState
	at org.mule.modules.salesforce.oauth.SalesforceOAuthConnectorOAuthClientFactory.makeObject(SalesforceOAuthConnectorOAuthClientFactory.java:34)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at org.mule.modules.salesforce.oauth.SalesforceOAuthConnectorOAuthManager.acquireAccessToken(SalesforceOAuthConnectorOAuthManager.java:397)
	at org.mule.modules.salesforce.oauth.SalesforceOAuthConnectorOAuthManager.acquireAccessToken(SalesforceOAuthConnectorOAuthManager.java:38)
	at org.mule.modules.salesforce.oauth.ManagedAccessTokenProcessInterceptor.execute(ManagedAccessTokenProcessInterceptor.java:53)
	at org.mule.modules.salesforce.oauth.ManagedAccessTokenProcessInterceptor.execute(ManagedAccessTokenProcessInterceptor.java:21)
	at org.mule.modules.salesforce.oauth.ManagedAccessTokenProcessTemplate.execute(ManagedAccessTokenProcessTemplate.java:32)
	at org.mule.modules.salesforce.processors.DescribeSObjectMessageProcessor.process(DescribeSObjectMessageProcessor.java:115)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:58)
```

It seems that SalesforceOAuthConnectorOAuthClientFactory creates a SalesforceOAuthConnectorOAuthState rather than a OAuthState.  Can this be updated to work with the new OAuthState object that is being used in the new version of Mule?

**Comment by veigap** [comment]
The issue seems to still be open. Reopen it.

**Comment by cambrozie** [comment]
Hey Eric. Could you please give me a project/flow which I can use to reproduce this?  

Just as a quick fix, you don't necessarily need to use an object store for OAuth as Mule will manage everything for you and you can focus on the operation flows.
